config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  resources :bases
  resources :users
  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "bases#index"
  namespace 'api' do
    resources :posts, defaults: {format: 'json'}
    resources :comments
    resources :health
  end
end

app/controllers/bases_controller.rb
class BasesController < ApplicationController
  before_action :set_basis, only: %i[ show edit update destroy ]

  # GET /bases or /bases.json
  def index
    @bases = Base.all
  end

  # GET /bases/1 or /bases/1.json
  def show
  end

  # GET /bases/new
  def new
    @basis = Base.new
  end

  # GET /bases/1/edit
  def edit
  end

  # POST /bases or /bases.json
  def create
    @basis = Base.create!(basis_params)
  end

  # PATCH/PUT /bases/1 or /bases/1.json
  def update
    @basis.update!(basis_params)
  end

  # DELETE /bases/1 or /bases/1.json
  def destroy
    @basis.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basis
      @basis = Base.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def basis_params
      params.fetch(:basis, {})
    end
end

app/helpers/bases_helper.rb
module BasesHelper
end

app/views/bases/_form.html.erb
<%= form_with(model: basis) do |form| %>
  <% if basis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(basis.errors.count, "error") %> prohibited this basis from being saved:</h2>

      <ul>
        <% basis.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bases/edit.html.erb
<h1>Editing Basis</h1>

<%= render 'form', basis: @basis %>

<%= link_to 'Show', @basis %> |
<%= link_to 'Back', bases_path %>

app/views/bases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bases</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bases.each do |basis| %>
      <tr>
        <td><%= link_to 'Show', basis %></td>
        <td><%= link_to 'Edit', edit_basis_path(basis) %></td>
        <td><%= link_to 'Destroy', basis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Basis', new_basis_path %>

app/views/bases/new.html.erb
<h1>New Basis</h1>

<%= render 'form', basis: @basis %>

<%= link_to 'Back', bases_path %>

app/views/bases/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_basis_path(@basis) %> |
<%= link_to 'Back', bases_path %>